### ISSUE TITLE
My Groups Section - View More count is wrong

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#10]
As shown in the picture, there is only one group I've joined, but it's written "2 More Groups, View More". I think there shouldn't be this "2 More groups, view more" text unless there are more than 4 or 5 groups. And also I think this should be applied to all lists.
<img width="489" alt="screen shot 2015-12-05 at 11 36 17" src="https://cloud.githubusercontent.com/assets/620104/11607168/f3ddcc72-9b44-11e5-9ae2-9f6ae9fb3b43.png">

@ssurucu @recepgunay53

**Comment by ssurucu** [comment]
fixed
