### ISSUE TITLE
The text of empty "Recommended For You" panel should be changed.

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#15]
The text of empty Recommended For You panel in Groups page seems to be too cynical, can we revise it?

"Sorry, we do not have any recommended groups, that meet your high personal skills and amazing interests"

**Comment by ssurucu** [comment]
@cakyel can you write the new text?

**Comment by cakyel** [comment]
"We do not have any group recommendations for you yet."

If you agree, this would be suitable.
