### ISSUE TITLE
Static content should be removed from Groups Page

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#2]
Static content should be removed from Groups Page
<img width="739" alt="screen shot 2015-11-26 at 23 37 34" src="https://cloud.githubusercontent.com/assets/620104/11430942/f4d2342e-9496-11e5-8a0b-aa3264955ff0.png">

**Comment by ssurucu** [comment]
Connected with this issue, there are two methods for listing all groups and my groups in the swagger. Are the services of Popular groups, latest groups and recommended for you completed? @mehmetcelikel @barisozcanli

**Comment by barisozcanli** [comment]
@ssurucu I created issues and I will implement Popular Groups and Latest Groups methods very soon.

**Comment by ssurucu** [comment]
there is no static content in groups page anymore, they are all coming from the services
