### ISSUE TITLE
Date time fileds : Date time picker

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#26]
Can we use date/time picker for date and time fields?
<img width="593" alt="screen shot 2015-12-09 at 22 10 04" src="https://cloud.githubusercontent.com/assets/620104/11697319/bcbd076e-9ec1-11e5-8b51-defa2c8a0a92.png">
<img width="903" alt="screen shot 2015-12-09 at 22 09 47" src="https://cloud.githubusercontent.com/assets/620104/11697323/be5cc352-9ec1-11e5-9ac9-09f0185e5950.png">

**Comment by ssurucu** [comment]
@barisozcanli yes, we can. we will add this.

**Comment by cakyel** [comment]
> **GIVEN** there is an existing group and the user is logged in,
> **WHEN** Create New Meeting page is loaded,
> **THEN** the date and time can be defined via Date/Time picker panel
- [x] Day in date/time picker can be selected
- [x] Month in date/time picker can be selected
- [x] Year in date/time picker can be selected
- [x] Date and time is saved when Save button is clicked

**Comment by cakyel** [comment]
@ssurucu this is functional in Create New Meeting, great news!

Can you implement it to Update Meeting also, if you have time?

**Comment by ssurucu** [comment]
@cakyel good news, I added to update meeting

**Comment by cakyel** [comment]
You are the best!
