### ISSUE TITLE
Create meeting : Warnings must be user friendly

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#28]
While creating meeting, is some mandatory fields are not filled, a message such "Error: HttpMessageNotReadable, Please check your request" is shown to the user. It must be user friendly such as "You should fill the mandatory fields."
<img width="1051" alt="screen shot 2015-12-09 at 22 16 32" src="https://cloud.githubusercontent.com/assets/620104/11697531/a6f51574-9ec2-11e5-8c2f-3a03bdd6b6cf.png">

**Comment by cakyel** [comment]
> **GIVEN** there is an existing group and the user is logged in and the user is in create new meeting page,
> **WHEN** the user misses a mandatory field and clicks Save button,
> **THEN** "You should fill mandatory fields" alert message must be shown
- [x] New meeting is created if mandatory fields are filled
- [x] New meeting is not created if mandatory fields are not filled
- [x] Alert message is shown when a mandatory field is not filled
- [x] Alert message is shown if multiple mandatory fields are not filled

**Comment by cakyel** [comment]
Tested OK

![image](https://cloud.githubusercontent.com/assets/4705964/12076962/96b599d6-b1cd-11e5-966e-a311e09ae83a.png)
