### ISSUE TITLE
Create Meeting: Invite users functionality is confusing

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#29]
Invite users functionality is confusing. I didn't understand how to use it. It must be improved.
<img width="589" alt="screen shot 2015-12-09 at 22 24 58" src="https://cloud.githubusercontent.com/assets/620104/11697752/d9081114-9ec3-11e5-9d04-575d7e145482.png">

**Comment by ssurucu** [comment]
@barisozcanli can you recommend the way how to improve it? you type for a user, and it autocompletes and selects, and you press the button invite. what is confusing here?

**Comment by cakyel** [comment]
@ssurucu maybe the only confusing part is the location of Invite All Users button. When some users are already invited, it looks like they are all users in the group and if you click Invite All Users they will be invited. But they are already invited!

In my opinion, the confusion would fade away if you position the Invite All Users button to right - top or right - bottom:

![image](https://cloud.githubusercontent.com/assets/4705964/11909912/082bccc2-a5f6-11e5-9478-77cc09cd3b4a.png)
