### ISSUE TITLE
Create Meeting : Discussion links must be removed or functional

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#30]
Currently when the discussion links are clicked, page changes and the data entered is lost. 
These links must be removed or be functional like being added to discussion list when clicked.

<img width="586" alt="screen shot 2015-12-09 at 22 27 33" src="https://cloud.githubusercontent.com/assets/620104/11697807/27d953c0-9ec4-11e5-97e9-06b5a7ff84d8.png">

**Comment by cakyel** [comment]
> **GIVEN** there is an existing group and the user is logged in and opened group details page,
> **WHEN**  a new discussion via group details page is created,
> **THEN** it should be shown in Discussions panel in group details page
> 
> **GIVEN** there is an existing group and the user is logged in and opened group details page and at least one discussion is created in it,
> **WHEN**  Discussions panel is loaded,
> **THEN** the discussion link must be functional
- [x] Discussions panel is loaded in group details page
- [ ] A new discussion can be related with the group via search tab in Discussions panel
- [ ] Multiple discussions can be related with the group via search tab in Discussions panel
- [x] A new created discussion via group details page is shown in Discussions panel in group details page
- [ ] Multiple new created discussions via group details page are shown in Discussion panel in group details page
- [ ] Related and new created disussions are shown together in Discussion panel in group details page
- [ ] User is redirected to discussion details page when a discussion name is clicked in Discussions panel
