### ISSUE TITLE
Group names must be unique

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#4]
Group names must be unique. It should not be allowed to use a group name which is already in the system.

**Comment by ssurucu** [comment]
it has to be handled in the backend system, and in case of an error we show the error message to the user. Can you check if it is handled in the backend?

**Comment by barisozcanli** [comment]
I created a new [issue](https://github.com/swe574-2015fall-group2/core_repo/issues/175) for this in the core-repo. I'll check it.

**Comment by barisozcanli** [comment]
Sinan,
  Mehmet commented on the issue that there is already a control on creating group.

@ssurucu @mehmetcelikel

**Comment by ssurucu** [comment]
![screen shot 2015-11-27 at 4 29 04 pm 1](https://cloud.githubusercontent.com/assets/6003528/11443260/2a735be8-9524-11e5-8fe9-33b030dd9587.png)

We also have this control, can you explain in which case you didn't get the error popup?

**Comment by barisozcanli** [comment]
Yes, I checked it, you're right. I must have mistaken. I think we can close this issue.
