### ISSUE TITLE
Register : Confusing message

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#43]
When an email which is already in the system entered in the register screen, this confusing message shown. It must be user friendly.

<img width="567" alt="screen shot 2015-12-12 at 10 39 46" src="https://cloud.githubusercontent.com/assets/620104/11761081/c38daf42-a0bc-11e5-8d84-18b5aa2b019c.png">

**Comment by ssurucu** [comment]
why is it in the webapp_repo? this is the message that server returns to the request, it must fixed on the server side. @barisozcanli
