### ISSUE TITLE
Profile screen : Archive profile functionality won't be implemented

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#44]
In the profile screen, archive profile button must be removed. This functionality won't be implemented in this phase.

<img width="322" alt="screen shot 2015-12-12 at 10 43 51" src="https://cloud.githubusercontent.com/assets/620104/11761095/52d78a10-a0bd-11e5-85f7-dc6f5101bb70.png">

**Comment by recepgunay53** [comment]
Fixed.
