### ISSUE TITLE
My Profile Screen : User data must be changed and static fields must be removed

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#45]
In my profile screen user name and last name are staticaly written such as Sinan Can.
User profile photo must be changed.
User data like university, programme, interested areas must be able to be updated.

*This issue must be broken down to respective issues. @cakyel 

<img width="1014" alt="screen shot 2015-12-12 at 10 45 13" src="https://cloud.githubusercontent.com/assets/620104/11761098/8ab147a0-a0bd-11e5-8bac-90257c76f346.png">

**Comment by cakyel** [comment]
Change user profile picture https://github.com/swe574-2015fall-group2/webapp_repo/issues/58

**Comment by cakyel** [comment]
Static name - surname to dynamic https://github.com/swe574-2015fall-group2/webapp_repo/issues/60

**Comment by cakyel** [comment]
User data revisions https://github.com/swe574-2015fall-group2/webapp_repo/issues/63
