### ISSUE TITLE
My profile : incorrect linkedin link

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#47]
probably academia link is also wrong
<img width="1044" alt="screen shot 2015-12-12 at 10 52 21" src="https://cloud.githubusercontent.com/assets/620104/11761126/897b302a-a0be-11e5-9dcb-9fc7aa868b0e.png">

**Comment by ssurucu** [comment]
what does this issue means? have you edited the area and the link didn't appear here? or you put a link and this links to the wrong page? what is the problem here?

**Comment by cakyel** [comment]
Hello Sinan,

Linkedin URL is pasted in front of Pink Elephant URL and it cannot be redirected to Linkedin:

![image](https://cloud.githubusercontent.com/assets/4705964/11871250/f9ecfb4c-a4d6-11e5-9be2-c514beee4026.png)

**Comment by cakyel** [comment]
> **GIVEN** there is an existing user account and the user is logged in and My Profile page is opened,
> **WHEN** the user clicks LinkedIn button, 
> **THEN** the user should be redirected to Linkedin in a new tab
- [x] My Profile page is loaded
- [x] Linkedin button is active if Linkedin link is saved
- [x] User is redirected to the saved Linkedin URL in a new tab
- [ ] Button is not active if there is no input
- [ ] Button is not active if there is no valid link

**Comment by ssurucu** [comment]
www.linkedin.com is not a valid profile url actually, that one you tried is one of a random url. linkedin profile url is in format of "https://tr.linkedin.com/in/sinan-can-surucu-b6098542". it should be with a http or https, anyway I put a control if the user intentionally deletes it.

**Comment by cakyel** [comment]
Hello,

I reopen this issue because,
- Button is active even if there is no link
- Invalid link control is not existing

**Comment by ssurucu** [comment]
@cakyel what do you mean by invalid link control?

**Comment by cakyel** [comment]
@ssurucu By the time Barış opened this issue, link was not redirecting to the specified URL. Now I checked it again and it is working. You can disregard that one.
