### ISSUE TITLE
My profile : feeds static page

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#48]
feeds tab should be removed. no reuirement, no implemented functionality.
<img width="893" alt="screen shot 2015-12-12 at 10 53 50" src="https://cloud.githubusercontent.com/assets/620104/11761138/bf200a34-a0be-11e5-8cfb-236bf8e0c786.png">

**Comment by recepgunay53** [comment]
Fixed.
