### ISSUE TITLE
Groups page : New user doesn't see any groups in the groups page.

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#49]
When a new user is created, in the groups page no group is shown. After creating a group, other groups are also shown in the popular groups or latest groups.

**Comment by ssurucu** [comment]
I think it was related with a backend issue, because it doesn't seem a problem now. with a new registered user, if you login, you see the groups in the page.

**Comment by cakyel** [comment]
Tested OK

![image](https://cloud.githubusercontent.com/assets/4705964/11918702/fc1d091e-a744-11e5-96bf-be1ad6a10939.png)
