### ISSUE TITLE
All Groups should be able to be viewed

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#5]
For now, all groups should be able to be viewed in the groups page. Or "view more" link should be functional.
<img width="748" alt="screen shot 2015-11-26 at 23 44 04" src="https://cloud.githubusercontent.com/assets/620104/11430989/bc7eeaf8-9497-11e5-8c18-6b81a04a48c3.png">

**Comment by ssurucu** [comment]
fixed
