### ISSUE TITLE
Create discussion

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#52]
One meeting should be able to be searched and added to the related meetings. This section should be improved.
<img width="927" alt="screen shot 2015-12-12 at 11 13 10" src="https://cloud.githubusercontent.com/assets/620104/11761205/8bc0c626-a0c1-11e5-9b2a-200784583488.png">

**Comment by cakyel** [comment]
https://github.com/swe574-2015fall-group2/webapp_repo/issues/31

**Comment by cakyel** [comment]
There is an existing issue, I copied your comment there and I am closing this one.
