### ISSUE TITLE
Create discussion : Resource section must be implemented

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#53]
A popup must be shown to search and list resources in the group.
A new resource should be able to be created here also.
Resources chosen should be able to be added to the resource list. And also resources should be able to be removed from the resources list.
<img width="647" alt="screen shot 2015-12-12 at 11 16 52" src="https://cloud.githubusercontent.com/assets/620104/11761216/ed2c7bb2-a0c1-11e5-8936-71acaf9814bc.png">

**Comment by cakyel** [comment]
> **GIVEN** there is an existing group and the user is in Create New Discussion page,
> **WHEN** a resource is listed in search bar and it is clicked and Save button is clicked,
> **THEN** the resource must be related with the discussion
- [ ] Resource can be listed via search bar
- [ ] Resource can be selected
- [ ] New discussion can be saved
