### ISSUE TITLE
Discussion detail page : Resources section must be implemented

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#54]
Resources section should be implemented
<img width="931" alt="screen shot 2015-12-12 at 11 19 43" src="https://cloud.githubusercontent.com/assets/620104/11761225/4f38b8e8-a0c2-11e5-9079-0ef713a5111c.png">

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there is an existing discussion in an existing group and the user is in discussion details page,
> **WHEN** the user selects a resource and clicks save button,
> **THEN** the resource is uploaded into the discussion.
- [ ] A resource can be selected
- [ ] A resource can be uploaded
