### ISSUE TITLE
Discussion detail : Resources section should be implemented

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#56]
<img width="726" alt="screen shot 2015-12-12 at 11 26 41" src="https://cloud.githubusercontent.com/assets/620104/11761251/4b007b8e-a0c3-11e5-954d-b339f4ff98d1.png">

**Comment by cakyel** [comment]
Related issue: https://github.com/swe574-2015fall-group2/webapp_repo/issues/35

**Comment by cakyel** [comment]
This is duplicate with https://github.com/swe574-2015fall-group2/webapp_repo/issues/54
