### ISSUE TITLE
Create Group error messages should be fixed

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#6]
When "Group Name" is not entered and clicked "Create Group" a message such as "Group Name must be entered" should be showed to the user. For the sake of user experience, it would be nice to show the error messages next to fields.

<img width="818" alt="screen shot 2015-11-26 at 23 46 14" src="https://cloud.githubusercontent.com/assets/620104/11431014/0a69c6b6-9498-11e5-91fe-f5934e927a08.png">

**Comment by cakyel** [comment]
> **GIVEN** the user is logged in and the user is in create new group page,
> **WHEN** the user misses a mandatory field and clicks Create Button button,
> **THEN** "You should fill mandatory fields" alert message must be shown
- [ ] New group is created if mandatory fields are filled
- [ ] New group is not created if mandatory fields are not filled
- [ ] Alert message is shown when a mandatory field is not filled
- [ ] Alert message is shown if multiple mandatory fields are not filled
