### ISSUE TITLE
Create Note : Related meeting and resources

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#61]
It should be same as #51 #52 #54 

<img width="1025" alt="screen shot 2015-12-12 at 11 34 57" src="https://cloud.githubusercontent.com/assets/620104/11761276/7153b930-a0c4-11e5-95b3-68502060a8ef.png">

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there is an existing group and the user is in Create New Note page
> **WHEN** a meeting is listed in search bar and it is clicked and Save button is clicked,
> **THEN** the meeting must be related with the note
- [ ] Meeting can be listed via search bar
- [ ] Meeting can be selected
- [ ] New note can be saved

> **GIVEN** there is an existing group and the user is in Create New Note page
> **WHEN** a resource is listed in search bar and it is clicked and Save button is clicked,
> **THEN** the resource must be related with the note
- [ ] Resource can be listed via search bar
- [ ] Resource can be selected
- [ ] New note can be saved
- [ ] New note can be saved with both meeting and resource is related
