### ISSUE TITLE
Profile : Privacy page should be implemented

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#62]
<img width="335" alt="screen shot 2015-12-12 at 11 39 23" src="https://cloud.githubusercontent.com/assets/620104/11761287/0b9ef54a-a0c5-11e5-8407-2b9cb068c6f0.png">

**Comment by cakyel** [comment]
I forgot that this issue was opened and created another issue. The other one is more detailed so I am closing this one.

https://github.com/swe574-2015fall-group2/webapp_repo/issues/78
