### ISSUE TITLE
My Profile - User data revisions

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#63]
- Birth Date should be listed in Info tab

![image](https://cloud.githubusercontent.com/assets/4705964/11761289/28ab02b4-a0c5-11e5-8347-23b5e890d43d.png)
- birthDate data attribute should be renamed as Birth Date

![image](https://cloud.githubusercontent.com/assets/4705964/11761293/4bf4202a-a0c5-11e5-9c72-0caf07a40ed6.png)

**Comment by recepgunay53** [comment]
fixed
