### ISSUE TITLE
Unnecessary cancel button in "Create Group Page"

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/webapp_repo#7]
Cancel button is unnecessary in "Create Group Page"

<img width="661" alt="screen shot 2015-11-26 at 23 50 08" src="https://cloud.githubusercontent.com/assets/620104/11431043/8c5c1b7e-9498-11e5-8793-6b2ba8b594c1.png">

**Comment by ssurucu** [comment]
Why is it unnecessary? It is not a thing that we invented, it is a common usage in web forms. What reason do we have to delete it?

**Comment by barisozcanli** [comment]
This form is not a pop-up window. In pop-ups when you click cancel it closes the pop-up and it's ofcourse necessary. But on this form if you give up creating a group, a button on top of the "create group page" named "return" or "back" would be nicer (IMHO). But ofcourse it's a design decision. Even if the choice is remaining the cancel button, it should be working. It's not working now.

**Comment by ssurucu** [comment]
fixed
