### ISSUE TITLE
Create New Meeting - Meeting Date should be revised

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#72]
Meeting date should be in date picker format or the date format should be specified to the user 

http://162.243.215.160/Content/#/new_meeting

![image](https://cloud.githubusercontent.com/assets/4705964/11761481/f66d5e66-a0cc-11e5-9781-b1fe0aa6b17c.png)

**Comment by ssurucu** [comment]
it is related to this issue; 

https://github.com/swe574-2015fall-group2/webapp_repo/issues/26
