### ISSUE TITLE
My Profile - "Any user can send me a message" should be pre-selected

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#78]
"Any user can send me a message" choice should be selected when the page is loaded.
- Can you also revise the text as: "**a** message" please?

![image](https://cloud.githubusercontent.com/assets/4705964/11767692/7ef22654-a1bd-11e5-8565-654407e3c0e7.png)

**Comment by cakyel** [comment]
If this issue also needs to be opened on the Back End side, please let me know. @recepgunay53 @ssurucu

**Comment by ssurucu** [comment]
@cakyel no we do not need that.
