### ISSUE TITLE
Update Meeting - Existing data should be shown in the page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#79]
When "Update Meeting" button is clicked in a meeting details page, existing meeting information should be shown in the Update Meeting page.

http://162.243.215.160/Content/#/update_meeting

![image](https://cloud.githubusercontent.com/assets/4705964/11855572/bb56c2ba-a453-11e5-9960-c5579618ee9c.png)

**Comment by cakyel** [comment]
## Test Cases

> **GIVEN** there is an existing meeting of an existing group and the user is in meeting details page,
> **WHEN** the user clicks Update Meeting button,
> **THEN** existing values of the meeting should be shown in Update Meeting page
- [x] Meeting Name field is filled
- [x] Description field is filled
- [x] Meeting Date field is filled
- [x] Meeting Hours - Start field is filled
- [x] Meeting Hours - End field is filled
- [x] Time Zone field is filled
- [x] Location field is filled
- [ ] Online Meeting tick is checked - if it is checked before
- [ ] Details field is filled - if it is filled before
- [ ] Related discussions are listed
- [ ] Invited users are listed - if any
- [ ] Agenda items are listed - if any
- [ ] To-Do items are listed - if any
- [x] The meeting can be updated

**Comment by ssurucu** [comment]
@cakyel can you try again? there seems no problem.

**Comment by cakyel** [comment]
@ssurucu the following cases are not functional:

 Online Meeting tick is checked - if it is checked before
 Details field is filled - if it is filled before
 Related discussions are listed
 Invited users are listed - if any
 Agenda items are listed - if any
 To-Do items are listed - if any

**Comment by cakyel** [comment]
## Test Case
- [ ] Open the following URL: http://162.243.215.160/
- [ ] Enter thomas@anderson.com to Username field
- [ ] Enter thomas123 to Password field
- [ ] Click Login button and see that Groups page is opened
- [ ] Click csdcs group name and see that group details page is opened
- [ ] Click "dene 2" button in Meetings panel and see that meeting details page is opened
- [ ] Click Update Meeting button and see that Update Meeting page is opened
- [ ] See that Contact Person Name field is listed
- [ ] See that Contact Person E-mail field is listed
- [ ] See that Contact Person Phone field is listed
- [ ] See that Meeting Name field is listed
- [ ] See that Meeting Description field is listed
- [ ] See that Meeting Date field is listed
- [ ] See that Timezone field is listed
- [ ] See that Invite List field is listed
- [ ] See that Location field is listed 
- [ ] See that Online Meeting field is listed
- [ ] See that Details field is listed
- [ ] See that Discussions field is listed
- [ ] See that Agenda Items field is listed
- [ ] See that To-Do list field is listed

**Comment by cakyel** [comment]
Some of the test cases are not correct in this issue but I specified them in here: https://github.com/swe574-2015fall-group2/webapp_repo/issues/87

So this issue can remain as closed as it is duplicate.
