### ISSUE TITLE
Registration Page - Form controls are missing

### ISSUE THREAD

**Issue by ssurucu** [swe574-2015fall-group2/webapp_repo#8]
(Closed related issue: https://github.com/swe574-2015fall-group2/core_repo/issues/182)

In the registration page, system accepts invalid e-mail address and does not check password field with the re-type password field.

https://onedrive.live.com/redir?resid=1571C717A54B2868!6575&authkey=!AC4qebyBIfew02A&v=3&ithint=photo%2cpng

**Comment by cakyel** [comment]
> **GIVEN** the user is in registration page,
> **WHEN** invalid e-mail address is added 
> **THEN** user must not be created and the user should be warned.
> 
> **GIVEN** the user is in registration page,
> **WHEN** passwords mismatch,
> **THEN** user must not be created and the user should be warned.
- [x] User is warned when invalid e-mail address is entered
- [x] User is warned in case of mismatch

**Comment by cakyel** [comment]
Tested OK

![image](https://cloud.githubusercontent.com/assets/4705964/12073013/46ca4ebe-b10d-11e5-9ccc-de717e6e12b2.png)

![image](https://cloud.githubusercontent.com/assets/4705964/12073014/5118c01c-b10d-11e5-8216-57a61b274712.png)
