### ISSUE TITLE
Update Note - Existing fields are not filled

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#97]
Existing fields of an opened note are not filled in Update Note page

http://162.243.215.160/Content/#/update_note

![image](https://cloud.githubusercontent.com/assets/4705964/11925777/94afd3d2-a7c7-11e5-9f8a-72854115b649.png)

**Comment by cakyel** [comment]
@ssurucu Existing fields are still not filled in Update Note page.

Example: Bananas group, çikita muz Note

I also get an error when I open Update Note page:

![image](https://cloud.githubusercontent.com/assets/4705964/12007493/bd281260-ac0f-11e5-886c-e550c885d91f.png)

**Comment by ssurucu** [comment]
@mehmetcelikel the commited code is not auto-deployed, can you help?

**Comment by ssurucu** [comment]
@mehmetcelikel the commited code is not auto-deployed, can you help?

**Comment by cakyel** [comment]
## Test Case
- [ ] Open the following URL: http://162.243.215.160/
- [ ] Enter thomas@anderson.com to Username field
- [ ] Enter thomas123 to Password field
- [ ] Click Login button and see that Groups page is opened
- [ ] Click csdcs group name and see that group details page is opened
- [ ] Click test 26.12.2015 note in the Notes panel and see that note details page is opened
- [ ] Click Update Note button and see that Update Note page is opened
- [ ] See that note fields are filled with existing data

**Comment by ssurucu** [comment]
@cakyel sorry but I can't reproduce the error, can you try again and tell me the details of your scenario? you can add your user/pass also so I can try

**Comment by cakyel** [comment]
@ssurucu the database is changed so this is obsolete but I found new bugs in the page:

Please login with amy@winehouse.com amy123

In the Amsterdam Lovers group open Test Note and click Update Note button. You will see;

1) Tags field is not semantic ready

![image](https://cloud.githubusercontent.com/assets/4705964/12072985/6cc6fe4c-b10c-11e5-8eef-e3b58e4dc380.png)

2) There are static related meetings

![image](https://cloud.githubusercontent.com/assets/4705964/12072987/73599ec2-b10c-11e5-92af-b34a746d7f6c.png)

3) When Delete button is clicked in a static meeting, user is redirected to groups page

![image](https://cloud.githubusercontent.com/assets/4705964/12072988/79b4f1e0-b10c-11e5-9f16-b1f9782f118c.png)

4) There are static resources in Resources tab

![image](https://cloud.githubusercontent.com/assets/4705964/12072991/8095e546-b10c-11e5-9180-fd5d436a592a.png)
