### ISSUE TITLE
Create New Note - Err: Meeting Not Found

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/webapp_repo#99]
I get an "Meeting Not Found" error when I try to create a new Note, while I haven't chosen any related meeting.

![image](https://cloud.githubusercontent.com/assets/4705964/11925826/f71b6112-a7c7-11e5-86b6-012d6f398461.png)

**Comment by ssurucu** [comment]
@cakyel can you try again? there seems no problem.

**Comment by cakyel** [comment]
@ssurucu I'm sorry I still get the error :(

![image](https://cloud.githubusercontent.com/assets/4705964/12011264/231d2398-accf-11e5-8514-7c076fab48a7.png)

## Test Case
- [ ] Open the following URL: http://162.243.215.160/
- [ ] Enter thomas@anderson.com to Username field
- [ ] Enter thomas123 to Password field
- [ ] Click Login button and see that Groups page is opened
- [ ] Click csdcs group name and see that group details page is opened
- [ ] Click the + button at the right of the page and click Create New Note button and see that Create New Note page is opened
- [ ] Enter "Test Note" to Note Name field
- [ ] Enter "Test Description" to Note Description field
- [ ] Click Create Note button and see the note created message
- [ ] See that user is redirected to note details page
- [ ] See that the note named as Test Note is on the Notes panel

**Comment by ssurucu** [comment]
@cakyel sorry but I can't reproduce the error, can you try again and tell me the details of your scenario? you can add your user/pass also so I can try

**Comment by cakyel** [comment]
@ssurucu The details were written in the Test Case section but the regarding group is not existing in the system. The user is also deleted I guess. So this is obsolete, I am closing the issue.
